import localFont from 'next/font/local';
import "./globals.css";

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-satoshi',
});

export const metadata = {
  title: "Victor Adeiza | Full-stack Engineer, Bridging AI and Web3",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` `}
      >
        {children}
      </body>
    </html>
  );
}
